# Generated by Django 4.0.3 on 2022-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email_field',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
